### ISSUE TITLE
On carina release binaries -  add OS type to title to make things clear for newbies

### ISSUE THREAD

**Issue by meker12** [getcarina/carina#39]
![releases_ _getcarina_carina](https://cloud.githubusercontent.com/assets/6391769/10717943/863ad92e-7b34-11e5-9862-58f2a6e4df55.png)

**Comment by rgbkrk** [comment]
I can't actually change the download title, it's the literal name of the binary (which is why you have to rename them after for non-Windows). As for the title of the release, that's more of a signifier of version that isn't just a number. I agree that for usability and folks not tied to development, these reasons don't make any sense.

We should make a real dedicated page with links to the binaries. This releases setup has been a stopgap while we iron this out.

**Comment by rgbkrk** [comment]
Forgot to say, thank you for pointing these out. I'll get a draft of a landing page for the client up and cc you on the PR.

**Comment by meker12** [comment]
Good to understand how it works.  Look forward to seeing the landing page. I guess when we have it, we'll need to update any links that point to the CLI download.  So far, I'm only aware of:  https://getcarina.com/docs/getting-started/getting-started-carina-cli/

**Comment by rgbkrk** [comment]
Closed by #70 (assuming release, which is ongoing).
